export default async function fetchProducts(supplementName) {
  const baseUrl = process.env.API_URL || 'https://localhost:8080/api/v1'
  if (!supplementName) {
    console.error('No supplement name provided for fetching products')
    return []
  }
  const url = `${baseUrl}/products?name=${encodeURIComponent(supplementName)}`
  try {
    const response = await fetch(url, {next: {revalidate: 36000}})
    if (!response.ok) {
      throw new Error(`Error fetching products: ${response.statusText}`)
    }
    const data = await response.json()
    return data.products || []
  } catch (error) {
    console.error('Failed to fetch products:', error)
    return []
  }
  // return [
  //   {
  //     name: 'Example Protein Powder',
  //     ingredients: ['Whey Protein Isolate', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.02,
  //     healthScore: 90.2,
  //     userScore: 89.6,
  //     servings: 30,
  //     unit: 'g',
  //     unitType: 'protein',
  //     unitAmount: 25,
  //     price: 29.99,
  //     filters: ['whey', 'isolate', 'natural'],
  //     link: 'https://example.com/product1',
  //     overall: 85,
  //   },
  //   {
  //     name: 'Example Plant-Based Protein',
  //     ingredients: ['Pea Protein', 'Brown Rice Protein', 'Natural Flavors'],
  //     pricePerUnit: 0.03,
  //     healthScore: 88.5,
  //     userScore: 87.4,
  //     filters: ['plant-based', 'pea', 'brown rice'],
  //     link: 'https://example.com/product2',
  //     overall: 82,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     filters: ['casein', 'slow-digesting'],
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     filters: ['casein', 'slow-digesting'],
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 44.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 99.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 15.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 80,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 99.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 79,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 91.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 78,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 77,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 77,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.001,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 75,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.004,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 75,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 70,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 65,
  //   },
  //   {
  //     name: 'Example Casein Protein',
  //     ingredients: ['Micellar Casein', 'Natural Flavors', 'Stevia'],
  //     pricePerUnit: 0.04,
  //     healthScore: 85.0,
  //     userScore: 84.3,
  //     link: 'https://example.com/product3',
  //     overall: 56,
  //   },
  // ]
}
